from django.urls import re_path, path
from .views import RenderIndex, GetEnvVars

urlpatterns = [
	re_path(r'^/?$', RenderIndex),
	re_path(r'^sign-up/?$', RenderIndex),
	re_path(r'^create-profile/?$', RenderIndex),
	re_path(r'^create-profile/42/?$', RenderIndex),
	re_path(r'^login/?$', RenderIndex),
	re_path(r'^login-42/?$', RenderIndex),
	re_path(r'^home/?$', RenderIndex),
	re_path(r'^home/?$', RenderIndex),
	re_path(r'^home/pong/?$', RenderIndex),
	re_path(r'^home/pong/single-player/?$', RenderIndex),
	re_path(r'^home/pong/multiplayer/?$', RenderIndex),
	re_path(r'^home/pong/multiplayer/waiting-room/2/?$', RenderIndex),
	re_path(r'^home/pong/multiplayer/waiting-room/4/?$', RenderIndex),
	re_path(r'^home/pong/single-player/tournament/?$', RenderIndex),
	re_path(r'^home/pong/multiplayer/tournament/?$', RenderIndex),
	re_path(r'^home/pong/play/?$', RenderIndex),
	re_path(r'^home/pong/play/single-player/1/?$', RenderIndex),
	re_path(r'^home/pong/play/single-player/2/?$', RenderIndex),
	re_path(r'^home/pong/play/multiplayer/2/?$', RenderIndex),
	re_path(r'^home/pong/play/multiplayer/4/?$', RenderIndex),
	re_path(r'^home/tic-tac-toe/?$', RenderIndex),
	re_path(r'^home/tic-tac-toe/single-player/?$', RenderIndex),
	re_path(r'^home/tic-tac-toe/multiplayer/?$', RenderIndex),
	re_path(r'^home/tic-tac-toe/multiplayer/waiting-room/2/?$', RenderIndex),
	re_path(r'^home/tic-tac-toe/single-player/tournament/?$', RenderIndex),
	re_path(r'^home/tic-tac-toe/multiplayer/tournament/?$', RenderIndex),
	re_path(r'^home/tic-tac-toe/play/?$', RenderIndex),
	re_path(r'^home/tic-tac-toe/play/single-player/1/?$', RenderIndex),
	re_path(r'^home/tic-tac-toe/play/single-player/2/?$', RenderIndex),
	re_path(r'^home/tic-tac-toe/play/multiplayer/2/?$', RenderIndex),
	re_path(r'^home/profile/?$', RenderIndex),
	re_path(r'^home/profile/username/?$', RenderIndex),
	re_path(r'^home/profile/password/?$', RenderIndex),
	re_path(r'^home/profile/avatar/?$', RenderIndex),

	path('get-env-vars', GetEnvVars, name='get_env_vars'),
]
