version: '3.8'
services:
  postgres:
    container_name: postgres
    image: postgres:13-alpine
    user: postgres
    env_file: .env
    expose:
      - "5432"
    networks:
      - transcendence
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U $POSTGRES_USER -d $POSTGRES_DB"]
      interval: 10s
      start_period: 10s
      retries: 5
    restart: always

  django-backend:
    container_name: app
    build: app/
    env_file: .env
    ports:
      - "8000:8000"
#    expose:
#      - "8000"
    networks:
      - transcendence
    depends_on:
      postgres:
        condition: service_healthy
    restart: on-failure

networks:
  transcendence:
    driver: bridge
