version: '3.8'
services:
  auth_service-postgres:
    container_name: auth_service-postgres
    image: postgres:13-alpine3.18
    user: postgres
    environment:
      POSTGRES_HOST_FILE: /run/secrets/auth_service-postgres_host
      POSTGRES_DB_FILE: /run/secrets/auth_service-postgres_db
      POSTGRES_USER_FILE: /run/secrets/auth_service-postgres_user
      POSTGRES_PASSWORD_FILE: /run/secrets/auth_service-postgres_password
    secrets:
      - auth_service-postgres_host
      - auth_service-postgres_db
      - auth_service-postgres_user
      - auth_service-postgres_password
    expose:
      - "5432"
    networks:
      - transcendence
    volumes:
      - auth_service-postgres_data:/var/lib/postgresql/data/:rw
    healthcheck:
      test: [ "CMD-SHELL", 'pg_isready -h "$(cat $POSTGRES_HOST_FILE)" -U "$(cat $POSTGRES_USER_FILE)" -d "$(cat $POSTGRES_DB_FILE)"' ]
      interval: 5s
      start_period: 5s
      retries: 5
    profiles: [ "", "auth_service" ]
    restart: always

  auth_service:
    container_name: auth_service
    build:
      context: auth_service/
      target: prod
    environment:
      POSTGRES_HOST_FILE: /run/secrets/auth_service-postgres_host
      POSTGRES_DB_FILE: /run/secrets/auth_service-postgres_db
      POSTGRES_USER_FILE: /run/secrets/auth_service-postgres_user
      POSTGRES_PASSWORD_FILE: /run/secrets/auth_service-postgres_password
      SSO_42_CLIENT_SECRET_FILE: /run/secrets/sso_42_client_secret
      SSO_42_REDIRECT_URI: ${SSO_42_REDIRECT_URI}
      SSO_42_CLIENT_ID: ${SSO_42_CLIENT_ID}
      DJANGO_ALLOWED_HOSTS: ${DJANGO_ALLOWED_HOSTS}
      VAULT_ADDR: https://modsecurity:8200
      VAULT_ROLE_ID_FILE: /vault/transcendence/transcendence-role-id
      VAULT_SECRET_ID_FILE: /vault/transcendence/transcendence-secret-id
      SSL_CERT_PATH: ${SSL_CERT_PATH}
      SSL_CERT_FILE: ${SSL_CERT_FILE}
      SSL_CERT_KEY_PATH: ${SSL_CERT_KEY_PATH}
      SSL_CERT_KEY_FILE: ${SSL_CERT_KEY_FILE}
    secrets:
      - auth_service-postgres_host
      - auth_service-postgres_db
      - auth_service-postgres_user
      - auth_service-postgres_password
      - sso_42_client_secret
    expose:
      - "8000"
    networks:
      - transcendence
    volumes:
      - auth_service-daphne_sock:/run/daphne/:rw
      - media_data:/app/media/:rw
      - ssl_cert_data:${SSL_CERT_PATH}:ro
      - ssl_cert_key_data:${SSL_CERT_KEY_PATH}:ro
      - vault_services_data:/vault/transcendence/:ro
    depends_on:
      auth_service-postgres:
        condition: service_healthy
      auth_service-db_migrations:
        condition: service_completed_successfully
      modsecurity:
        condition: service_started
      vault_service:
        condition: service_healthy
    profiles: [ "", "auth_service" ]
    restart: always

  game_service:
    container_name: game_service
    build:
      context: game_service/
      target: prod
    environment:
      REDIS_HOST: redis_service
      REDIS_PORT: 6379
      DJANGO_ALLOWED_HOSTS: ${DJANGO_ALLOWED_HOSTS}
      VAULT_ADDR: https://modsecurity:8200
      VAULT_ROLE_ID_FILE: /vault/transcendence/transcendence-role-id
      VAULT_SECRET_ID_FILE: /vault/transcendence/transcendence-secret-id
      SSL_CERT_PATH: ${SSL_CERT_PATH}
      SSL_CERT_FILE: ${SSL_CERT_FILE}
      SSL_CERT_KEY_PATH: ${SSL_CERT_KEY_PATH}
      SSL_CERT_KEY_FILE: ${SSL_CERT_KEY_FILE}
    expose:
      - "8000"
    networks:
      - transcendence
    volumes:
      - game_service-daphne_sock:/run/daphne/:rw
      - media_data:/app/media/:rw
      - ssl_cert_data:${SSL_CERT_PATH}:ro
      - ssl_cert_key_data:${SSL_CERT_KEY_PATH}:ro
      - vault_services_data:/vault/transcendence/:ro
    depends_on:
      redis_service:
        condition: service_healthy
      modsecurity:
        condition: service_started
      vault_service:
        condition: service_healthy
    profiles: [ "", "game_service" ]
    restart: always

  modsecurity:
    container_name: modsecurity
    build:
      context: .
      dockerfile: modsecurity-nginx/Dockerfile
      target: prod
      args:
        - SSL_CERT_PATH
        - SSL_CERT_FILE
        - SSL_CERT_KEY_PATH
        - SSL_CERT_KEY_FILE
    environment:
      # NGINX
      AUTH_SERVICE_BACKEND: http://unix:/run/daphne/auth_service/daphne.sock
      GAME_SERVICE_BACKEND: http://unix:/run/daphne/game_service/daphne.sock
      VAULT_SERVICE_BACKEND: https://vault_service:8200
      NGINX_ALWAYS_TLS_REDIRECT: on
      SSL_CERT_PATH: ${SSL_CERT_PATH}
      SSL_CERT_FILE: ${SSL_CERT_FILE}
      SSL_CERT_KEY_PATH: ${SSL_CERT_KEY_PATH}
      SSL_CERT_KEY_FILE: ${SSL_CERT_KEY_FILE}
      VAULT_PORT: 8200
      SSL_PORT: 8443
      PORT: 8080
      # ModSecurity
      MODSEC_RULE_ENGINE: On
      ANOMALY_INBOUND: 5
      ANOMALY_OUTBOUND: 4
      BLOCKING_PARANOIA: 2
      ALLOWED_METHODS: GET HEAD POST PUT DELETE OPTIONS
    ports:
      - "8080:8080"
      - "8200:8200"
      - "8443:8443"
    networks:
      - transcendence
    volumes:
      - auth_service-daphne_sock:/run/daphne/auth_service/:rw
      - game_service-daphne_sock:/run/daphne/game_service/:rw
      - web_service-data:/usr/share/nginx/html/:ro
      - static_data:/app/static/:ro
      - media_data:/app/media/:ro
      - ssl_cert_data:${SSL_CERT_PATH}:rw
      - ssl_cert_key_data:${SSL_CERT_KEY_PATH}:rw
      - telegraf_data:/var/log/telegraf/:rw
    profiles: [ "", "auth_service", "game_service", "web_service" ]
    restart: always

  redis_service:
    container_name: redis_service
    image: redis:7.2-alpine3.18
    expose:
      - "6379"
    networks:
      - transcendence
    healthcheck:
      test: [ "CMD-SHELL", 'redis-cli ping || exit 1' ]
      interval: 5s
      start_period: 5s
      retries: 5
    profiles: [ "", "game_service" ]
    restart: always

  vault_service:
    container_name: vault_service
    build:
      context: vault/
      target: service
      args:
        - SSL_CERT_PATH
        - SSL_CERT_FILE
        - SSL_CERT_KEY_PATH
        - SSL_CERT_KEY_FILE
    environment:
      VAULT_SKIP_VERIFY: true
    expose:
      - "8200"
    networks:
      - transcendence
    volumes:
      - ssl_cert_data:${SSL_CERT_PATH}:ro
      - ssl_cert_key_data:${SSL_CERT_KEY_PATH}:ro
    healthcheck:
      test: [ "CMD-SHELL", 'vault status' ]
      interval: 5s
      start_period: 5s
      retries: 5
    depends_on:
      modsecurity:
        condition: service_started
    cap_add:
      - IPC_LOCK
    profiles: [ "", "auth_service", "web_service" ]
    restart: always

  ############# TOOLS #############
  vault_service-init:
    container_name: vault_service-init
    build:
      context: vault/
      target: init
    environment:
      VAULT_ADDR: https://vault_service:8200
      VAULT_SKIP_VERIFY: true
      VAULT_CACERT: ${SSL_CERT_PATH}${SSL_CERT_FILE}
    networks:
      - transcendence
    volumes:
      - ssl_cert_data:${SSL_CERT_PATH}:ro
      - vault_keys_data:/vault/keys/:rw
      - vault_root_data:/vault/root/:rw
      - vault_services_data:/vault/transcendence/:rw
    depends_on:
      vault_service:
        condition: service_started
    restart: on-failure

  auth_service-db_migrations:
    container_name: auth_service-db_migrations
    build:
      context: auth_service/
      target: tools
    environment:
      POSTGRES_HOST_FILE: /run/secrets/auth_service-postgres_host
      POSTGRES_DB_FILE: /run/secrets/auth_service-postgres_db
      POSTGRES_USER_FILE: /run/secrets/auth_service-postgres_user
      POSTGRES_PASSWORD_FILE: /run/secrets/auth_service-postgres_password
      VAULT_ADDR: https://modsecurity:8200
      VAULT_ROLE_ID_FILE: /vault/transcendence/transcendence-role-id
      VAULT_SECRET_ID_FILE: /vault/transcendence/transcendence-secret-id
      SSL_CERT_PATH: ${SSL_CERT_PATH}
      SSL_CERT_FILE: ${SSL_CERT_FILE}
      SSL_CERT_KEY_PATH: ${SSL_CERT_KEY_PATH}
      SSL_CERT_KEY_FILE: ${SSL_CERT_KEY_FILE}
    secrets:
      - auth_service-postgres_host
      - auth_service-postgres_db
      - auth_service-postgres_user
      - auth_service-postgres_password
    entrypoint: [ "/bin/sh", "/app/tools/db-migrations.sh" ]
    networks:
      - transcendence
    volumes:
      - ssl_cert_data:${SSL_CERT_PATH}:ro
      - ssl_cert_key_data:${SSL_CERT_KEY_PATH}:ro
      - vault_services_data:/vault/transcendence/:ro
    depends_on:
      auth_service-postgres:
        condition: service_healthy
      vault_service:
        condition: service_healthy
    profiles: [ "", "auth_service", "tools" ]
    restart: on-failure

  auth_service-collectstatic:
    container_name: auth_service-collectstatic
    build:
      context: auth_service/
      target: tools
    environment:
      VAULT_ADDR: https://modsecurity:8200
      VAULT_ROLE_ID_FILE: /vault/transcendence/transcendence-role-id
      VAULT_SECRET_ID_FILE: /vault/transcendence/transcendence-secret-id
      SSL_CERT_PATH: ${SSL_CERT_PATH}
      SSL_CERT_FILE: ${SSL_CERT_FILE}
      SSL_CERT_KEY_PATH: ${SSL_CERT_KEY_PATH}
      SSL_CERT_KEY_FILE: ${SSL_CERT_KEY_FILE}
    entrypoint: [ "python3", "/app/manage.py", "collectstatic", "--noinput" ]
    networks:
      - transcendence
    volumes:
      - ./auth_service/:/app/:ro
      - static_data:/app/static/:rw
      - ssl_cert_data:${SSL_CERT_PATH}:ro
      - ssl_cert_key_data:${SSL_CERT_KEY_PATH}:ro
      - vault_services_data:/vault/transcendence/:ro
    depends_on:
      vault_service:
        condition: service_healthy
    profiles: [ "", "auth_service", "tools" ]
    restart: on-failure

  game_service-collectstatic:
    container_name: game_service-collectstatic
    build:
      context: auth_service/
      target: tools
    environment:
      VAULT_ADDR: https://modsecurity:8200
      VAULT_ROLE_ID_FILE: /vault/transcendence/transcendence-role-id
      VAULT_SECRET_ID_FILE: /vault/transcendence/transcendence-secret-id
      SSL_CERT_PATH: ${SSL_CERT_PATH}
      SSL_CERT_FILE: ${SSL_CERT_FILE}
      SSL_CERT_KEY_PATH: ${SSL_CERT_KEY_PATH}
      SSL_CERT_KEY_FILE: ${SSL_CERT_KEY_FILE}
    entrypoint: [ "python3", "/app/manage.py", "collectstatic", "--noinput" ]
    networks:
      - transcendence
    volumes:
      - ./game_service/:/app/:ro
      - static_data:/app/static/:rw
      - ssl_cert_data:${SSL_CERT_PATH}:ro
      - ssl_cert_key_data:${SSL_CERT_KEY_PATH}:ro
      - vault_services_data:/vault/transcendence/:ro
    depends_on:
      vault_service:
        condition: service_healthy
    profiles: [ "", "game_service", "tools" ]
    restart: on-failure

  web_service:
    container_name: web_service
    build:
      context: web_service/
      target: prod
    environment:
      SSO_42_CLIENT_ID: ${SSO_42_CLIENT_ID}
      SSO_42_REDIRECT_URI: ${SSO_42_REDIRECT_URI}
    volumes:
      - web_service-data:/app/:rw
      - vault_services_data:/vault/transcendence/:ro
    depends_on:
      vault_service:
        condition: service_healthy
    profiles: [ "", "web_service", "tools" ]
    restart: on-failure
  
  telegraf:
    container_name: telegraf
    build:
      context: monitoring/telegraf/
      args:
        - NGINX_METRICS_URL=https://modsecurity:8081/nginx_status
    restart: always
    networks:
      - transcendence
    volumes:
      - telegraf_data:/var/log/telegraf/:ro
    depends_on:
      auth_service:
        condition: service_started

  cadvisor:
    container_name: cadvisor
    image:  gcr.io/cadvisor/cadvisor:latest
    networks:
      - transcendence
    volumes:
      - /:/rootfs:ro
      - /var/run:/var/run:ro
      - /sys:/sys:ro
      - /var/lib/docker/:/var/lib/docker:ro
      - /dev/disk/:/dev/disk:ro
    privileged: true
    depends_on:
      auth_service:
        condition: service_started
    devices:
      - "/dev/kmsg"
    command:
      - '-port=9200'
  
  node-exporter:
    container_name: node-exporter
    image: prom/node-exporter:latest
    networks:
      - transcendence
    volumes:
      - /proc:/host/proc:ro
      - /sys:/host/sys:ro
      - /:/rootfs:ro
      - /:/host:ro,rslave
    privileged: true
    command:
      - '--path.procfs=/host/proc'
      - '--path.sysfs=/host/sys'
      - '--path.rootfs=/rootfs'
      - '--collector.filesystem.ignored-mount-points=^/(sys|proc|dev|host|etc|rootfs/var/lib/docker/containers|rootfs/var/lib/docker/overlay2|rootfs/run/docker/netns|rootfs/var/lib/docker/aufs)($$|/)'
    depends_on:
      auth_service:
        condition: service_started
    restart: always

  alertmanager:
    build:
      context: monitoring/alertmanager/
      args:
        SLACK_ALERTMANAGER_WEBHOOK: ${SLACK_ALERTMANAGER_WEBHOOK}
        SLACK_ALERTMANAGER_CHANNEL: ${SLACK_ALERTMANAGER_CHANNEL}
    container_name: alertmanager
    networks:
      - transcendence
    command:
      - '--config.file=/etc/alertmanager/alert.yml'
    restart: always
    depends_on:
      auth_service:
        condition: service_started

  prometheus:
    container_name: prometheus
    build:
      context: monitoring/prometheus/
      args:
        PROMETHEUS_ADDR: prometheus:9090
        PROMETHEUS_USER: ${MONITORING_USERNAME}
        PROMETHEUS_PASSWORD: ${MONITORING_PASSWORD}
        TELEGRAF_ADDR: telegraf:9125
        CADVISOR_ADDR: cadvisor:9200
        NODE_EXPORTER_ADDR: node-exporter:9100
        ALERTMANAGER_ADDR: alertmanager:9093
    restart: always
    user: root
    ports:
      - "9090:9090"
    volumes:
      - prometheus_data:/prometheus
    privileged: true
    networks:
      - transcendence
    command:
      - "--config.file=/etc/prometheus/prometheus.yml"
      - "--web.config.file=/etc/prometheus/web.yml"
    depends_on:
      telegraf:
        condition: service_started
      cadvisor:
        condition: service_started
      node-exporter:
        condition: service_started
      alertmanager:
        condition: service_started
  
  grafana:
    build:
      context: monitoring/grafana/
      args:
        PROMETHEUS_URL: http://prometheus:9090
        PROMETHEUS_USER: ${MONITORING_USERNAME}
        PROMETHEUS_PASSWORD: ${MONITORING_PASSWORD}
    container_name: grafana
    restart: always
    ports:
      - "3000:3000"
    volumes:
      - grafana_data:/var/lib/grafana
    networks:
      - transcendence
    environment:
      GF_SECURITY_ADMIN_USER: ${MONITORING_USERNAME}
      GF_SECURITY_ADMIN_PASSWORD: ${MONITORING_PASSWORD}
      GF_DASHBOARDS_DEFAULT_HOME_DASHBOARD_PATH: /etc/grafana/dashboards/Home.json
    depends_on:
      prometheus:
        condition: service_started

  nikto:
    container_name: nikto
    build:
      context: nikto/
    environment:
      WEB_ADDR: https://modsecurity:8443
    networks:
      - transcendence
    volumes:
      - ./nikto/output/:/git/nikto/output/:rw
    depends_on:
      modsecurity:
        condition: service_started
    profiles: [ "web_service", "tools" ]

networks:
  transcendence:
    driver: bridge

volumes:
  auth_service-postgres_data:
  auth_service-daphne_sock:
  game_service-daphne_sock:
  web_service-data:
  static_data:
  media_data:

  ssl_cert_data:
  ssl_cert_key_data:

  vault_root_data:
  vault_keys_data:
  vault_services_data:

  prometheus_data:
  grafana_data:
  telegraf_data:

secrets:
  auth_service-postgres_host:
    file: ./secrets/auth_service/postgres-host
  auth_service-postgres_db:
    file: ./secrets/auth_service/postgres-db
  auth_service-postgres_user:
    file: ./secrets/auth_service/postgres-user
  auth_service-postgres_password:
    file: ./secrets/auth_service/postgres-password
  sso_42_client_secret:
    file: ./secrets/42-client-secret
    