route:
  group_by: [cluster]
  receiver: alert-test
  group_wait: 3s
  group_interval: 5s
  repeat_interval: 1m
  routes:
    - match:
        severity: slack
        receiver: alert-test

receivers:
- name: alert-test
  slack_configs:
  - api_url: $SLACK_ALERTMANAGER_WEBHOOK
    channel: $SLACK_ALERTMANAGER_CHANNEL
    icon_url: https://avatars3.githubusercontent.com/u/3380462
    send_resolved: true
    text: "<!channel> \nsummary: {{ .CommonAnnotations.summary }}\ndescription: {{ .CommonAnnotations.description }}"
