global:
  scrape_interval: 15s
  external_labels:
    monitor: 'codelab-monitor'

scrape_configs:
  - job_name: 'prometheus'

    scrape_interval: 5s

    static_configs:
      - targets: ['$PROMETHEUS_ADDR']
      - targets: ['$PROMETHEUS_EXPORTER_ADDR']