global:
  scrape_interval: 15s
  external_labels:
    monitor: 'codelab-monitor'

scrape_configs:
  - job_name: 'prometheus'
    scrape_interval: 5s
    static_configs:
      - targets: ['$PROMETHEUS_ADDR']
  
  - job_name: Telegraf
    scrape_interval: 5s
    static_configs:
      - targets: ['$TELEGRAF_ADDR'] 